version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: rag-health-redis
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight
    environment:
      - REDIS_ARGS=--save 60 1000
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: rag-health-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WANDB_API_KEY=${WANDB_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000

volumes:
  redis-data:
