[project]
name = "rag-health-evals"
version = "0.1.0"
description = "W&B evaluation suite"
requires-python = ">=3.11"
dependencies = [
    "rag-health-core",
    "wandb>=0.18.0",
    "httpx>=0.27.0",
]

[tool.uv.sources]
rag-health-core = { workspace = true }
